import 'dua_l10n_map.dart';

/// Extra UI strings (nav, Center hub, knowledge). All supported [languageCode]s included;
/// missing entries should not occur — fallback is handled in [lookupAppExtra].
final Map<String, Map<String, String>> kAppExtra = {
  ...duaL10nEntries,
  'navHome': {
    'tr': 'Ana Sayfa',
    'en': 'Home',
    'ar': 'الرئيسية',
    'ur': 'ہوم',
    'id': 'Beranda',
    'fa': 'خانه',
    'bn': 'হোম',
    'ms': 'Utama',
    'fr': 'Accueil',
    'de': 'Startseite',
    'es': 'Inicio',
    'ru': 'Главная',
    'hi': 'होम',
    'sw': 'Nyumbani',
    'ml': 'ഹോം',
    'uz': 'Bosh sahifa',
    'ps': 'کور',
    'ha': 'Gida',
    'ta': 'முகப்பு',
    'fil': 'Home',
    'az': 'Ana səhifə',
    'so': 'Bogga',
  },
  'sectionQuickAccess': {
    'tr': 'Hızlı Erişim',
    'en': 'Quick access',
    'ar': 'وصول سريع',
    'ur': 'فوری رسائی',
    'id': 'Akses cepat',
    'fa': 'دسترسی سریع',
    'bn': 'দ্রুত অ্যাক্সেস',
    'ms': 'Akses pantas',
    'fr': 'Accès rapide',
    'de': 'Schnellzugriff',
    'es': 'Acceso rápido',
    'ru': 'Быстрый доступ',
    'hi': 'त्वरित पहुँच',
    'sw': 'Ufikiaji wa haraka',
    'ml': 'വേഗത്തിലുള്ള പ്രവേശനം',
    'uz': 'Tezkor kirish',
    'ps': 'ګړندی لاسرسی',
    'ha': 'Saurin shiga',
    'ta': 'விரைவு அணுகல்',
    'fil': 'Mabilis na access',
    'az': 'Sürətli giriş',
    'so': 'Helitaan degdeg ah',
  },
  'sectionKnowledgeLibrary': {
    'tr': 'İslami Bilgi Kütüphanesi',
    'en': 'Islamic knowledge library',
    'ar': 'مكتبة المعرفة الإسلامية',
    'ur': 'اسلامی علم کی لائبریری',
    'id': 'Perpustakaan pengetahuan Islam',
    'fa': 'کتابخانه دانش اسلامی',
    'bn': 'ইসলামিক জ্ঞানের গ্রন্থাগার',
    'ms': 'Perpustakaan ilmu Islam',
    'fr': 'Bibliothèque de savoir islamique',
    'de': 'Islamische Wissensbibliothek',
    'es': 'Biblioteca de conocimiento islámico',
    'ru': 'Библиотека исламских знаний',
    'hi': 'इस्लामी ज्ञान पुस्तकालय',
    'sw': 'Maktaba ya maarifa ya Kiislamu',
    'ml': 'ഇസ്ലാമിക് വിജ്ഞാന ലൈബ്രറി',
    'uz': 'Islomiy bilim kutubxonasi',
    'ps': 'د اسلامي پوهې کتابتون',
    'ha': 'Library ilimin Musulunci',
    'ta': 'இஸ்லாமிய அறிவு நூலகம்',
    'fil': 'Aklatan ng kaalaman sa Islam',
    'az': 'İslam bilik kitabxanası',
    'so': 'Maktabadda aqoonta Islaamka',
  },
  'sectionCommunity': {
    'tr': 'Topluluk',
    'en': 'Community',
    'ar': 'المجتمع',
    'ur': 'کمیونٹی',
    'id': 'Komunitas',
    'fa': 'جامعه',
    'bn': 'সম্প্রদায়',
    'ms': 'Komuniti',
    'fr': 'Communauté',
    'de': 'Gemeinschaft',
    'es': 'Comunidad',
    'ru': 'Сообщество',
    'hi': 'समुदाय',
    'sw': 'Jumuiya',
    'ml': 'കമ്മ്യൂണിറ്റി',
    'uz': 'Jamiyat',
    'ps': 'ټولنه',
    'ha': 'Al\'umma',
    'ta': 'சமூகம்',
    'fil': 'Komunidad',
    'az': 'İcma',
    'so': 'Bulshada',
  },
  'prayerTimesChip': {
    'tr': 'Namaz Vakitleri',
    'en': 'Prayer times',
    'ar': 'أوقات الصلاة',
    'ur': 'نماز کے اوقات',
    'id': 'Waktu shalat',
    'fa': 'اوقات نماز',
    'bn': 'নামাজের সময়',
    'ms': 'Waktu solat',
    'fr': 'Horaires de prière',
    'de': 'Gebetszeiten',
    'es': 'Horarios de oración',
    'ru': 'Время намаза',
    'hi': 'नमाज़ के समय',
    'sw': 'Nyakati za sala',
    'ml': 'നമസ്കാര സമയം',
    'uz': 'Namoz vaqtlari',
    'ps': 'د لمونځ وختونه',
    'ha': 'Lokutan sallah',
    'ta': 'தொழுகை நேரங்கள்',
    'fil': 'Oras ng dasal',
    'az': 'Namaz vaxtları',
    'so': 'Waqtiyada salaadda',
  },
  'nextNamazLabel': {
    'tr': 'Sıradaki Namaz',
    'en': 'Next prayer',
    'ar': 'الصلاة التالية',
    'ur': 'اگلی نماز',
    'id': 'Shalat berikutnya',
    'fa': 'نماز بعدی',
    'bn': 'পরবর্তী নামাজ',
    'ms': 'Solat seterusnya',
    'fr': 'Prochaine prière',
    'de': 'Nächstes Gebet',
    'es': 'Próxima oración',
    'ru': 'Следующий намаз',
    'hi': 'अगली नमाज़',
    'sw': 'Sala inayofuata',
    'ml': 'അടുത്ത നമസ്കാരം',
    'uz': 'Keyingi namoz',
    'ps': 'راتلونکی لمونځ',
    'ha': 'Sallah mai zuwa',
    'ta': 'அடுத்த தொழுகை',
    'fil': 'Susunod na dasal',
    'az': 'Növbəti namaz',
    'so': 'Salaadda xigta',
  },
  'tapForPrayerTimes': {
    'tr': 'Namaz vakitleri için dokun',
    'en': 'Tap for prayer times',
    'ar': 'اضغط لأوقات الصلاة',
    'ur': 'نماز کے اوقات کے لیے تھپتھپائیں',
    'id': 'Ketuk untuk waktu shalat',
    'fa': 'برای اوقات نماز ضربه بزنید',
    'bn': 'নামাজের সময়ের জন্য ট্যাপ করুন',
    'ms': 'Ketik untuk waktu solat',
    'fr': 'Appuyez pour les horaires',
    'de': 'Tippen für Gebetszeiten',
    'es': 'Toca para horarios de oración',
    'ru': 'Нажмите для времени намаза',
    'hi': 'नमाज़ के समय के लिए टैप करें',
    'sw': 'Gusa kwa nyakati za sala',
    'ml': 'നമസ്കാര സമയത്തിന് ടാപ്പ് ചെയ്യുക',
    'uz': 'Namoz vaqtlari uchun bosing',
    'ps': 'د لمونځ وختونو لپاره ټپ وکړئ',
    'ha': 'Taɓa don lokutan sallah',
    'ta': 'தொழுகை நேரத்திற்கு தட்டவும்',
    'fil': 'I-tap para sa oras ng dasal',
    'az': 'Namaz vaxtları üçün toxunun',
    'so': 'Taabo waqtiyada salaadda',
  },
  'timePassed': {
    'tr': 'Vakit geçti',
    'en': 'Time passed',
    'ar': 'انتهى الوقت',
    'ur': 'وقت گزر چکا',
    'id': 'Waktu telah lewat',
    'fa': 'زمان گذشت',
    'bn': 'সময় শেষ',
    'ms': 'Masa telah berlalu',
    'fr': 'Temps écoulé',
    'de': 'Zeit vorbei',
    'es': 'Tiempo pasado',
    'ru': 'Время прошло',
    'hi': 'समय बीत गया',
    'sw': 'Muda umepita',
    'ml': 'സമയം കഴിഞ്ഞു',
    'uz': 'Vaqt oʻtdi',
    'ps': 'وخت تېر شو',
    'ha': 'Lokaci ya wuce',
    'ta': 'நேரம் கடந்தது',
    'fil': 'Lumipas na ang oras',
    'az': 'Vaxt keçdi',
    'so': 'Waqtigu wuu dhammaaday',
  },
  'countdownHM': {
    'tr': '{h} sa {m} dk',
    'en': '{h}h {m}m',
    'ar': '{h} س {m} د',
    'ur': '{h} گھ {m} من',
    'id': '{h} j {m} m',
    'fa': '{h} س {m} د',
    'bn': '{h} ঘ {m} মি',
    'ms': '{h} j {m} min',
    'fr': '{h} h {m} min',
    'de': '{h} Std. {m} Min.',
    'es': '{h} h {m} min',
    'ru': '{h} ч {m} мин',
    'hi': '{h} घं {m} मि',
    'sw': '{h} h {m} dk',
    'ml': '{h} മ {m} മി',
    'uz': '{h} s {m} d',
    'ps': '{h} س {m} م',
    'ha': '{h} h {m} m',
    'ta': '{h} ம {m} நி',
    'fil': '{h} h {m} m',
    'az': '{h} s {m} d',
    'so': '{h} s {m} d',
  },
  'countdownMS': {
    'tr': '{m} dk {s} sn',
    'en': '{m}m {s}s',
    'ar': '{m} د {s} ث',
    'ur': '{m} من {s} س',
    'id': '{m} m {s} d',
    'fa': '{m} د {s} ث',
    'bn': '{m} মি {s} সে',
    'ms': '{m} min {s} saat',
    'fr': '{m} min {s} s',
    'de': '{m} Min. {s} Sek.',
    'es': '{m} min {s} s',
    'ru': '{m} мин {s} с',
    'hi': '{m} मि {s} से',
    'sw': '{m} dk {s} sk',
    'ml': '{m} മി {s} സെ',
    'uz': '{m} d {s} s',
    'ps': '{m} م {s} ث',
    'ha': '{m} m {s} s',
    'ta': '{m} நி {s} வி',
    'fil': '{m} m {s} s',
    'az': '{m} d {s} s',
    'so': '{m} d {s} s',
  },
  'countdownS': {
    'tr': '{s} sn',
    'en': '{s}s',
    'ar': '{s} ث',
    'ur': '{s} س',
    'id': '{s} d',
    'fa': '{s} ث',
    'bn': '{s} সে',
    'ms': '{s} s',
    'fr': '{s} s',
    'de': '{s} Sek.',
    'es': '{s} s',
    'ru': '{s} с',
    'hi': '{s} से',
    'sw': '{s} sk',
    'ml': '{s} സെ',
    'uz': '{s} s',
    'ps': '{s} ث',
    'ha': '{s} s',
    'ta': '{s} வி',
    'fil': '{s} s',
    'az': '{s} s',
    'so': '{s} s',
  },
  'lastPrayerPrefix': {
    'tr': 'Son:',
    'en': 'Last:',
    'ar': 'آخر:',
    'ur': 'آخری:',
    'id': 'Terakhir:',
    'fa': 'آخرین:',
    'bn': 'শেষ:',
    'ms': 'Akhir:',
    'fr': 'Dernière :',
    'de': 'Zuletzt:',
    'es': 'Última:',
    'ru': 'Последняя:',
    'hi': 'अंतिम:',
    'sw': 'Mwisho:',
    'ml': 'അവസാനം:',
    'uz': 'Oxirgi:',
    'ps': 'وروستی:',
    'ha': 'Na karshe:',
    'ta': 'கடைசி:',
    'fil': 'Huli:',
    'az': 'Son:',
    'so': 'Ugu dambeeyay:',
  },
  'quickPrayerTitle': {
    'tr': 'Namaz Vakitleri',
    'en': 'Prayer times',
    'ar': 'أوقات الصلاة',
    'ur': 'نماز کے اوقات',
    'id': 'Waktu shalat',
    'fa': 'اوقات نماز',
    'bn': 'নামাজের সময়',
    'ms': 'Waktu solat',
    'fr': 'Horaires de prière',
    'de': 'Gebetszeiten',
    'es': 'Horarios de oración',
    'ru': 'Время намаза',
    'hi': 'नमाज़ के समय',
    'sw': 'Nyakati za sala',
    'ml': 'നമസ്കാര സമയം',
    'uz': 'Namoz vaqtlari',
    'ps': 'د لمونځ وختونه',
    'ha': 'Lokutan sallah',
    'ta': 'தொழுகை நேரங்கள்',
    'fil': 'Oras ng dasal',
    'az': 'Namaz vaxtları',
    'so': 'Waqtiyada salaadda',
  },
  'quickPrayerSub': {
    'tr': 'Günlük 6 vakit',
    'en': 'Six daily prayers',
    'ar': 'ست صلوات يومية',
    'ur': 'روزانہ چھ نمازیں',
    'id': 'Enam shalat harian',
    'fa': 'شش نماز روزانه',
    'bn': 'দৈনিক ছয় ওয়াক্ত',
    'ms': 'Enam waktu sehari',
    'fr': 'Six prières quotidiennes',
    'de': 'Sechs tägliche Gebete',
    'es': 'Seis oraciones diarias',
    'ru': 'Шесть ежедневных молитв',
    'hi': 'छह दैनिक नमाज़',
    'sw': 'Sala sita za kila siku',
    'ml': 'ദിവസവും ആറ് നമസ്കാരം',
    'uz': 'Kuniga oltita namoz',
    'ps': 'ورځني شپږ لمونځ',
    'ha': 'Sallah shida na yau da kullun',
    'ta': 'நாள்தோறும் ஆறு தொழுகை',
    'fil': 'Anim na dasal araw-araw',
    'az': 'Gündəlik altı namaz',
    'so': 'Lix salaadood maalin kasta',
  },
  'quickDhikrTitle': {
    'tr': 'Zikir Sayacı',
    'en': 'Dhikr counter',
    'ar': 'عداد الذكر',
    'ur': 'ذکر شمار',
    'id': 'Penghitung dzikir',
    'fa': 'شمارنده ذکر',
    'bn': 'জিকির কাউন্টার',
    'ms': 'Pembilang zikir',
    'fr': 'Compteur de dhikr',
    'de': 'Dhikr-Zähler',
    'es': 'Contador de dhikr',
    'ru': 'Счётчик зикра',
    'hi': 'ज़िक्र काउंटर',
    'sw': 'Kipiga hesabu cha dhikr',
    'ml': 'ധിക്ര് കൗണ്ടർ',
    'uz': 'Zikr hisoblagichi',
    'ps': 'د ذکر شمېرونکی',
    'ha': 'Mai ƙidayar dhikr',
    'ta': 'ஜிக்ர் எண்ணி',
    'fil': 'Tagabilang ng dhikr',
    'az': 'Zikir sayğacı',
    'so': 'Tiraya dhikr',
  },
  'quickDhikrSub': {
    'tr': 'Subhanallah · Elhamdülillah',
    'en': 'Subhanallah · Alhamdulillah',
    'ar': 'سبحان الله · الحمد لله',
    'ur': 'سبحان اللہ · الحمدللہ',
    'id': 'Subhanallah · Alhamdulillah',
    'fa': 'سبحان‌الله · الحمدلله',
    'bn': 'সুবহানাল্লাহ · আলহামদুলিল্লাহ',
    'ms': 'Subhanallah · Alhamdulillah',
    'fr': 'Subhanallah · Alhamdulillah',
    'de': 'Subhanallah · Alhamdulillah',
    'es': 'Subhanallah · Alhamdulillah',
    'ru': 'Субханаллах · Альхамдулиллях',
    'hi': 'सुभानअल्लाह · अल्हम्दुलिल्लाह',
    'sw': 'Subhanallah · Alhamdulillah',
    'ml': 'സുബ്ഹാനല്ലാഹ് · അൽഹംദുലില്ലാഹ്',
    'uz': 'Subhanalloh · Alhamdulillah',
    'ps': 'سبحان الله · الحمد لله',
    'ha': 'Subhanallah · Alhamdulillah',
    'ta': 'சுப்ஹானல்லாஹ் · அல்ஹம்துலில்லாஹ்',
    'fil': 'Subhanallah · Alhamdulillah',
    'az': 'Subhanallah · Əlhəmdulillah',
    'so': 'Subhanallah · Alhamdulillah',
  },
  'quickCalTitle': {
    'tr': 'İslami Takvim',
    'en': 'Islamic calendar',
    'ar': 'التقويم الإسلامي',
    'ur': 'اسلامی کیلنڈر',
    'id': 'Kalender Islam',
    'fa': 'تقویم اسلامی',
    'bn': 'ইসলামিক ক্যালেন্ডার',
    'ms': 'Kalendar Islam',
    'fr': 'Calendrier islamique',
    'de': 'Islamischer Kalender',
    'es': 'Calendario islámico',
    'ru': 'Исламский календарь',
    'hi': 'इस्लामी कैलेंडर',
    'sw': 'Kalenda ya Kiislamu',
    'ml': 'ഇസ്ലാമിക് കലണ്ടർ',
    'uz': 'Islom taqvimi',
    'ps': 'اسلامي کلینډر',
    'ha': 'Kalanda Musulunci',
    'ta': 'இஸ்லாமிய நாட்காட்டி',
    'fil': 'Islamikong kalendaryo',
    'az': 'İslam təqvimi',
    'so': 'Kalandarka Islaamka',
  },
  'quickCalSub': {
    'tr': 'Hicri tarih & mübarek günler',
    'en': 'Hijri dates & blessed days',
    'ar': 'التاريخ الهجري والأيام المباركة',
    'ur': 'ہجری تاریخیں اور مبارک دن',
    'id': 'Tanggal Hijriah & hari berkah',
    'fa': 'تاریخ قمری و روزهای مبارک',
    'bn': 'হিজরি তারিখ ও পবিত্র দিন',
    'ms': 'Tarikh Hijrah & hari mulia',
    'fr': 'Dates hijri & jours bénis',
    'de': 'Hidschra-Daten & gesegnete Tage',
    'es': 'Fechas hijri y días bendecidos',
    'ru': 'Хиджра и благословенные дни',
    'hi': 'हिजरी तिथियाँ और पवित्र दिन',
    'sw': 'Tarehe za Hijra & siku takatifu',
    'ml': 'ഹിജ്റ തീയതികളും വിശുദ്ധ ദിനങ്ങളും',
    'uz': 'Hijriy sanalar va muqaddas kunlar',
    'ps': 'هجري نېټې او برکت ورځې',
    'ha': 'Kwanan wata na Hijira & kwanaki masu albarka',
    'ta': 'ஹிஜ்ரி தேதிகள் & ஆசீர்வதிக்கப்பட்ட நாட்கள்',
    'fil': 'Hijri at mga araw na pinagpala',
    'az': 'Hicri tarixlər və müqəddəs günlər',
    'so': 'Taariikhda Hijrada & maalmaha barakaysan',
  },
  'quickGoalsTitle': {
    'tr': 'Okuma Hedefleri',
    'en': 'Reading goals',
    'ar': 'أهداف القراءة',
    'ur': 'پڑھنے کے اہداف',
    'id': 'Target membaca',
    'fa': 'اهداف مطالعه',
    'bn': 'পঠন লক্ষ্য',
    'ms': 'Sasaran bacaan',
    'fr': 'Objectifs de lecture',
    'de': 'Leseziele',
    'es': 'Metas de lectura',
    'ru': 'Цели чтения',
    'hi': 'पढ़ने के लक्ष्य',
    'sw': 'Malengo ya kusoma',
    'ml': 'വായന ലക്ഷ്യങ്ങൾ',
    'uz': 'O\'qish maqsadlari',
    'ps': 'د لوستلو اهداف',
    'ha': 'Manufofin karatu',
    'ta': 'படிப்பு இலக்குகள்',
    'fil': 'Mga layunin sa pagbabasa',
    'az': 'Oxu məqsədləri',
    'so': 'Hadafyada akhriska',
  },
  'quickGoalsSub': {
    'tr': 'Günlük Kur\'an takibi',
    'en': 'Daily Quran tracking',
    'ar': 'متابعة القرآن اليومية',
    'ur': 'روزانہ قرآن کی پیروی',
    'id': 'Pelacakan Quran harian',
    'fa': 'پیگیری روزانه قرآن',
    'bn': 'দৈনিক কুরআন ট্র্যাকিং',
    'ms': 'Penjejak Quran harian',
    'fr': 'Suivi quotidien du Coran',
    'de': 'Tägliches Quran-Tracking',
    'es': 'Seguimiento diario del Corán',
    'ru': 'Ежедневное чтение Корана',
    'hi': 'दैनिक कुरआन ट्रैकिंग',
    'sw': 'Ufuatiliaji wa Kurani kila siku',
    'ml': 'ദൈനംദിന ഖുർആൻ ട്രാക്കിംഗ്',
    'uz': 'Kunlik Qur\'on kuzatuvi',
    'ps': 'ورځني قرآن تعقیب',
    'ha': 'Bin diddigar da Alkur\'ani yau da kullun',
    'ta': 'தினசரி குர்ஆன் கண்காணிப்பு',
    'fil': 'Araw-araw na pagsubaybay sa Quran',
    'az': 'Gündəlik Qur\'an izləmə',
    'so': 'Raadinta Qur\'aanka maalinlaha ah',
  },
  'knowledgeHubTitle': {
    'tr': 'Bilgi Kütüphanesi',
    'en': 'Knowledge library',
    'ar': 'مكتبة المعرفة',
    'ur': 'علم کی لائبریری',
    'id': 'Perpustakaan pengetahuan',
    'fa': 'کتابخانه دانش',
    'bn': 'জ্ঞানের গ্রন্থাগার',
    'ms': 'Perpustakaan ilmu',
    'fr': 'Bibliothèque de savoir',
    'de': 'Wissensbibliothek',
    'es': 'Biblioteca de conocimiento',
    'ru': 'Библиотека знаний',
    'hi': 'ज्ञान पुस्तकालय',
    'sw': 'Maktaba ya maarifa',
    'ml': 'വിജ്ഞാന ലൈബ്രറി',
    'uz': 'Bilim kutubxonasi',
    'ps': 'د پوهې کتابتون',
    'ha': 'Library ilimi',
    'ta': 'அறிவு நூலகம்',
    'fil': 'Aklatan ng kaalaman',
    'az': 'Bilik kitabxanası',
    'so': 'Maktabadda aqoonta',
  },
  'changeLanguage': {
    'tr': 'Dil Değiştir',
    'en': 'Change language',
    'ar': 'تغيير اللغة',
    'ur': 'زبان تبدیل کریں',
    'id': 'Ganti bahasa',
    'fa': 'تغییر زبان',
    'bn': 'ভাষা পরিবর্তন',
    'ms': 'Tukar bahasa',
    'fr': 'Changer de langue',
    'de': 'Sprache ändern',
    'es': 'Cambiar idioma',
    'ru': 'Сменить язык',
    'hi': 'भाषा बदलें',
    'sw': 'Badilisha lugha',
    'ml': 'ഭാഷ മാറ്റുക',
    'uz': 'Tilni o\'zgartirish',
    'ps': 'ژبه بدل کړئ',
    'ha': 'Canza harshe',
    'ta': 'மொழியை மாற்று',
    'fil': 'Palitan ang wika',
    'az': 'Dili dəyişdirin',
    'so': 'Beddel luqadda',
  },
  'communityBadgeUpper': {
    'tr': 'TOPLULUK',
    'en': 'COMMUNITY',
    'ar': 'المجتمع',
    'ur': 'کمیونٹی',
    'id': 'KOMUNITAS',
    'fa': 'جامعه',
    'bn': 'সম্প্রদায়',
    'ms': 'KOMUNITI',
    'fr': 'COMMUNAUTÉ',
    'de': 'GEMEINSCHAFT',
    'es': 'COMUNIDAD',
    'ru': 'СООБЩЕСТВО',
    'hi': 'समुदाय',
    'sw': 'JUMUIYA',
    'ml': 'കമ്മ്യൂണിറ്റി',
    'uz': 'JAMIYAT',
    'ps': 'ټولنه',
    'ha': 'AL\'UMMA',
    'ta': 'சமூகம்',
    'fil': 'KOMUNIDAD',
    'az': 'İCMA',
    'so': 'BULSHADA',
  },
  'duaBrotherhoodTitle': {
    'tr': 'Dua Kardeşliği',
    'en': 'Dua brotherhood',
    'ar': 'أخوية الدعاء',
    'ur': 'دعا بھائی چارہ',
    'id': 'Persaudaraan doa',
    'fa': 'برادری دعا',
    'bn': 'দোয়া ভ্রাতৃত্ব',
    'ms': 'Persaudaraan doa',
    'fr': 'Fraternité de dua',
    'de': 'Gebetsbruderschaft',
    'es': 'Hermandad de dua',
    'ru': 'Братство дуа',
    'hi': 'दुआ भाईचारा',
    'sw': 'Udugu wa dua',
    'ml': 'ദുആ സാഹോദര്യം',
    'uz': 'Duo birodarligi',
    'ps': 'د دعا ورورولي',
    'ha': "Yan uwana na addu'a",
    'ta': 'துஆ சகோதரத்துவம்',
    'fil': 'Kapatiran ng dua',
    'az': 'Dua qardaşlığı',
    'so': 'Walaaltinimada dua',
  },
  'duaBrotherhoodSub': {
    'tr': 'Aynı anda dua zincirine katılın; birlikte tamamlayın.',
    'en': 'Join a dua chain at the same time; complete it together.',
    'ar': 'انضم إلى سلسلة دعاء في نفس الوقت؛ أكملها معًا.',
    'ur': 'ایک ہی وقت میں دعا کے سلسلے میں شامل ہوں؛ مل کر مکمل کریں۔',
    'id': 'Gabung rantai doa bersama; selesaikan bersama.',
    'fa': 'به زنجیره دعا بپیوندید؛ با هم تکمیل کنید.',
    'bn': 'একই সময়ে দোয়ার শৃঙ্খলায় যোগ দিন; একসাথে সম্পূর্ণ করুন।',
    'ms': 'Sertai rangkaian doa serentak; lengkapkan bersama.',
    'fr': 'Rejoignez une chaîne de prières ; terminez-la ensemble.',
    'de': 'Tritt einer gemeinsamen Gebetskette bei; vollendet sie zusammen.',
    'es': 'Únete a una cadena de dua; complétala juntos.',
    'ru': 'Присоединяйтесь к цепочке дуа; завершите вместе.',
    'hi': 'एक साथ दुआ की कड़ी में शामिल हों; साथ पूरा करें।',
    'sw': 'Jiunge na mnyororo wa dua pamoja; kamilisha pamoja.',
    'ml': 'ഒരേ സമയം ദുആ ചെയിൻ ചേർന്ന് ചേർന്ന് പൂർത്തിയാക്കുക.',
    'uz': 'Bir vaqtning o\'zida duo zanjiriga qo\'shiling; birga yakunlang.',
    'ps': 'په یو وخت کې د دعا زنګیرې ته ګډون وکړئ؛ یوځای بشپړ کړئ.',
    'ha': 'Shiga jerin addu\'a a lokaci guda; kammata tare.',
    'ta': 'ஒரே நேரத்தில் துஆ சங்கிலியில் சேருங்கள்; ஒன்றாக முடிக்கவும்.',
    'fil': 'Sumali sa kadena ng dua nang sabay-sabay; tapusin nang magkasama.',
    'az': 'Eyni vaxtda dua zəncirinə qoşulun; birlikdə tamamlayın.',
    'so': 'Isla waqtiga ku biir silsiladda dua; wada dhammaystir.',
  },
  'duaBrotherhoodJoin': {
    'tr': 'Katıl',
    'en': 'Join',
    'ar': 'انضم',
    'ur': 'شامل ہوں',
    'id': 'Gabung',
    'fa': 'بپیوندید',
    'bn': 'যোগ দিন',
    'ms': 'Sertai',
    'fr': 'Rejoindre',
    'de': 'Mitmachen',
    'es': 'Unirse',
    'ru': 'Присоединиться',
    'hi': 'शामिल हों',
    'sw': 'Jiunge',
    'ml': 'ചേരുക',
    'uz': 'Qo\'shilish',
    'ps': 'ګډون',
    'ha': 'Shiga',
    'ta': 'சேரவும்',
    'fil': 'Sumali',
    'az': 'Qoşul',
    'so': 'Ku biir',
  },
  'km_pillars_islam_t': {
    'tr': "İslam'ın Şartları",
    'en': 'Pillars of Islam',
    'ar': 'أركان الإسلام',
    'ur': 'اسلام کے ستون',
    'id': 'Rukun Islam',
    'fa': 'ارکان اسلام',
    'bn': 'ইসলামের স্তম্ভ',
    'ms': 'Rukun Islam',
    'fr': 'Piliers de l’islam',
    'de': 'Säulen des Islam',
    'es': 'Pilares del islam',
    'ru': 'Столпы ислама',
    'hi': 'इस्लाम के स्तंभ',
    'sw': 'Nguzo za Uislamu',
    'ml': 'ഇസ്ലാമിന്റെ തൂണുകൾ',
    'uz': 'Islomning ustunlari',
    'ps': 'د اسلام ستونونه',
    'ha': 'Ginshikan Musulunci',
    'ta': 'இஸ்லாத்தின் தூண்கள்',
    'fil': 'Mga haligi ng Islam',
    'az': 'İslamın sütunları',
    'so': 'Tiirarka Islaamka',
  },
  'km_pillars_islam_s': {
    'tr': '5 temel şart',
    'en': 'Five pillars',
    'ar': 'خمسة أركان',
    'ur': 'پانچ ارکان',
    'id': 'Lima rukun',
    'fa': 'پنج رکن',
    'bn': 'পাঁচটি স্তম্ভ',
    'ms': 'Lima rukun',
    'fr': 'Cinq piliers',
    'de': 'Fünf Säulen',
    'es': 'Cinco pilares',
    'ru': 'Пять столпов',
    'hi': 'पाँच स्तंभ',
    'sw': 'Nguzo tano',
    'ml': 'അഞ്ച് തൂണുകൾ',
    'uz': 'Besh ustun',
    'ps': 'پنږ تونونه',
    'ha': 'Ginshika biyar',
    'ta': 'ஐந்து தூண்கள்',
    'fil': 'Limang haligi',
    'az': 'Beş sütun',
    'so': 'Shan tiir',
  },
  'km_pillars_faith_t': {
    'tr': 'İmanın Şartları',
    'en': 'Pillars of faith',
    'ar': 'أركان الإيمان',
    'ur': 'ایمان کے ارکان',
    'id': 'Rukun iman',
    'fa': 'ارکان ایمان',
    'bn': 'ঈমানের স্তম্ভ',
    'ms': 'Rukun iman',
    'fr': 'Piliers de la foi',
    'de': 'Glaubenssäulen',
    'es': 'Pilares de la fe',
    'ru': 'Столпы веры',
    'hi': 'ईमान के स्तंभ',
    'sw': 'Nguzo za imani',
    'ml': 'വിശ്വാസത്തിന്റെ തൂണുകൾ',
    'uz': 'Imon ustunlari',
    'ps': 'د ایمان ارکان',
    'ha': 'Ginshikan imani',
    'ta': 'நம்பிக்கையின் தூண்கள்',
    'fil': 'Mga haligi ng pananampalataya',
    'az': 'İmanın sütunları',
    'so': 'Tiirarka iimaanka',
  },
  'km_pillars_faith_s': {
    'tr': '6 iman esası',
    'en': 'Six articles of faith',
    'ar': 'ستة أركان للإيمان',
    'ur': 'چھ ایمان کے اصول',
    'id': 'Enam rukun iman',
    'fa': 'شش اصل ایمان',
    'bn': 'ছয়টি ঈমানের স্তম্ভ',
    'ms': 'Enam rukun iman',
    'fr': 'Six articles de foi',
    'de': 'Sechs Glaubensartikel',
    'es': 'Seis artículos de fe',
    'ru': 'Шесть статей веры',
    'hi': 'छह ईमान के सिद्धांत',
    'sw': 'Makala sita za imani',
    'ml': 'ആറ് വിശ്വാസ തത്വങ്ങൾ',
    'uz': 'Imonning oltita tamoyili',
    'ps': 'د ایمان شپږ اصولونه',
    'ha': 'Matakai shida na imani',
    'ta': 'ஆறு நம்பிக்கைக் கோட்பாடுகள்',
    'fil': 'Anim na artikulo ng pananampalataya',
    'az': 'İmanın altı prinsipi',
    'so': 'Lixda aasaaska iimaanka',
  },
  'km_esmaul_husna_t': {
    'tr': "Esmaü'l-Hüsna",
    'en': 'The Beautiful Names',
    'ar': 'أسماء الله الحسنى',
    'ur': 'اسماء الحسنی',
    'id': 'Asmaul Husna',
    'fa': 'اسماء الحسنی',
    'bn': 'আসমাউল হুসনা',
    'ms': 'Asmaul Husna',
    'fr': 'Les beaux noms d’Allah',
    'de': 'Die schönen Namen Allahs',
    'es': 'Los hermosos nombres',
    'ru': 'Прекрасные имена',
    'hi': 'अल्लाह के सुंदर नाम',
    'sw': 'Majina mazuri ya Mwenyezi Mungu',
    'ml': 'അല്ലാഹുവിന്റെ നല്ല നാമങ്ങൾ',
    'uz': 'Go\'zal ismlar',
    'ps': 'د الله ښې نومونه',
    'ha': 'Kyawawan sunayen Allah',
    'ta': 'அழகிய நாமங்கள்',
    'fil': 'Ang magagandang pangalan',
    'az': 'Gözəl adlar',
    'so': 'Magacyada quruxda badan',
  },
  'km_esmaul_husna_s': {
    'tr': "Allah'ın 99 ismi",
    'en': "The 99 names of Allah",
    'ar': 'تسعة وتسعون اسماً لله',
    'ur': 'اللہ کے ۹۹ نام',
    'id': '99 nama Allah',
    'fa': '۹۹ نام خداوند',
    'bn': 'আল্লাহর ৯৯ নাম',
    'ms': '99 nama Allah',
    'fr': 'Les 99 noms d’Allah',
    'de': 'Die 99 Namen Allahs',
    'es': 'Los 99 nombres de Alá',
    'ru': '99 имён Аллаха',
    'hi': 'अल्लाह के 99 नाम',
    'sw': 'Majina 99 ya Mwenyezi Mungu',
    'ml': 'അല്ലാഹുവിന്റെ 99 നാമങ്ങൾ',
    'uz': 'Allohning 99 ismi',
    'ps': 'د الله ۹۹ نومونه',
    'ha': 'Sunayen Allah 99',
    'ta': 'அல்லாஹ்வின் 99 நாமங்கள்',
    'fil': 'Ang 99 pangalan ng Allah',
    'az': 'Allahın 99 adı',
    'so': '99 magac ee Alle',
  },
  'km_six_kalima_t': {
    'tr': '6 Kelime-i Şehadet',
    'en': 'Six kalimas',
    'ar': 'الكلمات الست',
    'ur': 'چھ کلمے',
    'id': 'Enam kalimah',
    'fa': 'شش کلمه',
    'bn': 'ছয় কালিমা',
    'ms': 'Enam kalimah',
    'fr': 'Six kalimas',
    'de': 'Sechs Kalimas',
    'es': 'Seis kalimas',
    'ru': 'Шесть калым',
    'hi': 'छह कलीमे',
    'sw': 'Kalima sita',
    'ml': 'ആറ് കലിമകൾ',
    'uz': 'Oltita kalima',
    'ps': 'شپږ کلمې',
    'ha': 'Kalima shida',
    'ta': 'ஆறு கலிமாக்கள்',
    'fil': 'Anim na kalima',
    'az': 'Altı kəlmə',
    'so': 'Lix eray',
  },
  'km_six_kalima_s': {
    'tr': 'Okunuş ve anlam',
    'en': 'Recitation and meaning',
    'ar': 'التلاوة والمعنى',
    'ur': 'تلاوت اور معنی',
    'id': 'Bacaan dan makna',
    'fa': 'قرائت و معنا',
    'bn': 'তিলাওয়াত ও অর্থ',
    'ms': 'Bacaan dan maksud',
    'fr': 'Récitation et sens',
    'de': 'Rezitation und Bedeutung',
    'es': 'Recitación y significado',
    'ru': 'Чтение и смысл',
    'hi': 'तिलावत और अर्थ',
    'sw': 'Kusoma na maana',
    'ml': 'വായനയും അർത്ഥവും',
    'uz': 'O\'qish va ma\'no',
    'ps': 'تلاوت او معنی',
    'ha': 'Karatun da ma\'ana',
    'ta': 'ஓதுதல் மற்றும் பொருள்',
    'fil': 'Pagbigkas at kahulugan',
    'az': 'Oxunuş və mənası',
    'so': 'Akhri iyo macnaha',
  },
  'km_siyer_t': {
    'tr': 'Siyer-i Nebi',
    'en': 'Prophetic biography',
    'ar': 'السيرة النبوية',
    'ur': 'سیرت نبوی',
    'id': 'Sirah Nabi',
    'fa': 'سیره نبوی',
    'bn': 'সিরাতুন নবী',
    'ms': 'Sirah Nabi',
    'fr': 'Biographie prophétique',
    'de': 'Biografie des Propheten',
    'es': 'Biografía profética',
    'ru': 'Сира пророка',
    'hi': 'पैगंबर की जीवनी',
    'sw': 'Wasifu wa Nabii',
    'ml': 'പ്രവാചക ജീവചരിത്രം',
    'uz': 'Peyg\'ambar tarjimai holi',
    'ps': 'د نبي ژوندلیک',
    'ha': 'Tarihin Annabi',
    'ta': 'தீர்க்கதரிசி வாழ்க்கை',
    'fil': 'Talambuhay ng propeta',
    'az': 'Peyğəmbər tərcümeyi-halı',
    'so': 'Taariikhda Nebi',
  },
  'km_siyer_s': {
    'tr': 'Hz. Muhammed (s.a.v.)',
    'en': 'Prophet Muhammad ﷺ',
    'ar': 'النبي محمد ﷺ',
    'ur': 'حضرت محمد ﷺ',
    'id': 'Nabi Muhammad ﷺ',
    'fa': 'پیامبر محمد ﷺ',
    'bn': 'হজরত মুহাম্মদ ﷺ',
    'ms': 'Nabi Muhammad ﷺ',
    'fr': 'Prophète Muhammad ﷺ',
    'de': 'Prophet Muhammad ﷺ',
    'es': 'Profeta Muhammad ﷺ',
    'ru': 'Пророк Мухаммад ﷺ',
    'hi': 'पैगंबर मुहम्मद ﷺ',
    'sw': 'Nabii Muhammad ﷺ',
    'ml': 'പ്രവാചകൻ മുഹമ്മദ് ﷺ',
    'uz': 'Payg\'ambar Muhammad ﷺ',
    'ps': 'نبي محمد ﷺ',
    'ha': 'Annabi Muhammad ﷺ',
    'ta': 'நபி முஹம்மது ﷺ',
    'fil': 'Propeta Muhammad ﷺ',
    'az': 'Peyğəmbər Məhəmməd ﷺ',
    'so': 'Nabi Muxammad ﷺ',
  },
  'km_fiqh_basics_t': {
    'tr': 'Fıkhi Bilgiler',
    'en': 'Basic fiqh',
    'ar': 'فقه أساسي',
    'ur': 'بنیادی فقہ',
    'id': 'Fiqih dasar',
    'fa': 'فقه پایه',
    'bn': 'মৌলিক ফিকহ',
    'ms': 'Fiqah asas',
    'fr': 'Fiqh de base',
    'de': 'Grundlagen des Fiqh',
    'es': 'Fiqh básico',
    'ru': 'Основы фикха',
    'hi': 'मूल फ़िक़्ह',
    'sw': 'Fiqh ya msingi',
    'ml': 'അടിസ്ഥാന ഫിഖ്',
    'uz': 'Asosiy fiqh',
    'ps': 'اساسي فقه',
    'ha': 'Fiqh na asali',
    'ta': 'அடிப்படை ஃபிக்ஹ்',
    'fil': 'Pangunahing fiqh',
    'az': 'Əsas fiqh',
    'so': 'Fiqh aasaasi',
  },
  'km_fiqh_basics_s': {
    'tr': 'Temel fıkıh kuralları',
    'en': 'Essential rulings',
    'ar': 'أحكام أساسية',
    'ur': 'ضروری احکام',
    'id': 'Hukum penting',
    'fa': 'احکام ضروری',
    'bn': 'প্রয়োজনীয় বিধান',
    'ms': 'Hukum asas',
    'fr': 'Règles essentielles',
    'de': 'Wichtige Regeln',
    'es': 'Normas esenciales',
    'ru': 'Основные правила',
    'hi': 'महत्वपूर्ण नियम',
    'sw': 'Sheria muhimu',
    'ml': 'അടിസ്ഥാന നിയമങ്ങൾ',
    'uz': 'Asosiy qoidalar',
    'ps': 'مهم احکامات',
    'ha': 'Muhimman dokoki',
    'ta': 'அத்தியாவசிய விதிகள்',
    'fil': 'Mahahalagang tuntunin',
    'az': 'Əsas qaydalar',
    'so': 'Xeerarka aasaasiga ah',
  },
  'km_terms_t': {
    'tr': 'Terimler Sözlüğü',
    'en': 'Glossary of terms',
    'ar': 'معجم المصطلحات',
    'ur': 'اصطلاحات کی لغت',
    'id': 'Glosarium istilah',
    'fa': 'واژه‌نامه',
    'bn': 'শব্দকোষ',
    'ms': 'Glosari istilah',
    'fr': 'Glossaire',
    'de': 'Glossar',
    'es': 'Glosario',
    'ru': 'Глоссарий',
    'hi': 'शब्दावली',
    'sw': 'Kamusi ya maneno',
    'ml': 'പദാവലി',
    'uz': 'Lug\'at',
    'ps': 'اصطلاحات',
    'ha': 'Kamusin kalmomi',
    'ta': 'சொற்களஞ்சியம்',
    'fil': 'Talasalitaan',
    'az': 'Lüğət',
    'so': 'Erayada',
  },
  'km_terms_s': {
    'tr': 'İslami kavramlar',
    'en': 'Islamic concepts',
    'ar': 'مفاهيم إسلامية',
    'ur': 'اسلامی تصورات',
    'id': 'Konsep Islam',
    'fa': 'مفاهیم اسلامی',
    'bn': 'ইসলামিক ধারণা',
    'ms': 'Konsep Islam',
    'fr': 'Concepts islamiques',
    'de': 'Islamische Konzepte',
    'es': 'Conceptos islámicos',
    'ru': 'Исламские понятия',
    'hi': 'इस्लामी अवधारणाएँ',
    'sw': 'Dhana za Kiislamu',
    'ml': 'ഇസ്ലാമിക് ആശയങ്ങൾ',
    'uz': 'Islomiy tushunchalar',
    'ps': 'اسلامي مفاهیم',
    'ha': 'Fahimtar Musulunci',
    'ta': 'இஸ்லாமிய கருத்துகள்',
    'fil': 'Mga konsepto sa Islam',
    'az': 'İslam anlayışları',
    'so': 'Fikradaha Islaamka',
  },
  'km_interesting_facts_t': {
    'tr': 'İlginç Bilgiler',
    'en': 'Interesting facts',
    'ar': 'معلومات ممتعة',
    'ur': 'دلچسپ حقائق',
    'id': 'Fakta menarik',
    'fa': 'حقایق جالب',
    'bn': 'মজার তথ্য',
    'ms': 'Fakta menarik',
    'fr': 'Faits intéressants',
    'de': 'Interessante Fakten',
    'es': 'Datos curiosos',
    'ru': 'Интересные факты',
    'hi': 'रोचक तथ्य',
    'sw': 'Ukweli wa kuvutia',
    'ml': 'രസകരമായ വസ്തുതകൾ',
    'uz': 'Qiziqarli faktlar',
    'ps': 'په زړه پورې حقایق',
    'ha': 'Gaskiyoyi masu ban sha\'awa',
    'ta': 'சுவாரசியமான உண்மைகள்',
    'fil': 'Mga kawili-wiling katotohanan',
    'az': 'Maraqlı faktlar',
    'so': 'Xaqiiqooyin xiiso leh',
  },
  'km_interesting_facts_s': {
    'tr': 'Genel kültür',
    'en': 'General knowledge',
    'ar': 'ثقافة عامة',
    'ur': 'عمومی علم',
    'id': 'Pengetahuan umum',
    'fa': 'دانش عمومی',
    'bn': 'সাধারণ জ্ঞান',
    'ms': 'Pengetahuan am',
    'fr': 'Culture générale',
    'de': 'Allgemeinwissen',
    'es': 'Cultura general',
    'ru': 'Общие знания',
    'hi': 'सामान्य ज्ञान',
    'sw': 'Maarifa ya jumla',
    'ml': 'പൊതുവിജ്ഞാനം',
    'uz': 'Umumiy bilim',
    'ps': 'عمومي پوهه',
    'ha': 'Sanin gabaɗaya',
    'ta': 'பொது அறிவு',
    'fil': 'Pangkalahatang kaalaman',
    'az': 'Ümumi məlumat',
    'so': 'Aqoonta guud',
  },
  'dashboardPrayerTomorrow': {
    'tr': 'YARIN',
    'en': 'TOMORROW',
    'ar': 'غداً',
    'ur': 'کل',
    'id': 'BESOK',
    'fa': 'فردا',
    'bn': 'আগামীকাল',
    'ms': 'ESOK',
    'fr': 'DEMAIN',
    'de': 'MORGEN',
    'es': 'MAÑANA',
    'ru': 'ЗАВТРА',
    'hi': 'कल',
    'sw': 'KESHO',
    'ml': 'നാളെ',
    'uz': 'ERTAGA',
    'ps': 'سبا',
    'ha': 'GOBE',
    'ta': 'நாளை',
    'fil': 'BUKAS',
    'az': 'SABAH',
    'so': 'BERI',
  },
  'dashboardPrayerNext': {
    'tr': 'SONRAKI VAKİT',
    'en': 'NEXT PRAYER',
    'ar': 'الصلاة التالية',
    'ur': 'اگلی نماز',
    'id': 'SHALAT BERIKUTNYA',
    'fa': 'نماز بعدی',
    'bn': 'পরবর্তী নামাজ',
    'ms': 'SOLAT SETERUSNYA',
    'fr': 'PROCHAINE PRIÈRE',
    'de': 'NÄCHSTES GEBET',
    'es': 'PRÓXIMA ORACIÓN',
    'ru': 'СЛЕДУЮЩИЙ НАМАЗ',
    'hi': 'अगली नमाज़',
    'sw': 'SALA INAYOFUATA',
    'ml': 'അടുത്ത നമസ്കാരം',
    'uz': 'KEYINGI NAMOZ',
    'ps': 'راتلونکی لمونځ',
    'ha': 'SALLAH MAI ZUWA',
    'ta': 'அடுத்த தொழுகை',
    'fil': 'SUSUNOD NA DASAL',
    'az': 'NÖVBƏTİ NAMAZ',
    'so': 'SALAADDA XIGTA',
  },
  'premium_feat_download_l': {
    'tr': 'Offline Ses',
    'en': 'Offline audio',
    'de': 'Offline-Audio',
  },
  'premium_feat_download_d': {
    'tr': 'İnternetsiz dinle',
    'en': 'Listen without internet',
    'de': 'Ohne Internet hören',
  },
  'premium_feat_reciters_l': {
    'tr': 'Tüm Kariler',
    'en': 'All reciters',
    'de': 'Alle Rezitatoren',
  },
  'premium_feat_reciters_d': {
    'tr': 'Hafız sesleri',
    'en': 'Qāriʾ voices',
    'de': 'Stimmen der Rezitatoren',
  },
  'premium_feat_tajweed_l': {
    'tr': 'Tecvid Pro',
    'en': 'Tajweed Pro',
    'de': 'Tadschwīd Pro',
  },
  'premium_feat_tajweed_d': {
    'tr': 'Gelişmiş renkler',
    'en': 'Advanced colours',
    'de': 'Erweiterte Farben',
  },
  'premium_feat_stats_l': {
    'tr': 'İstatistikler',
    'en': 'Statistics',
    'de': 'Statistiken',
  },
  'premium_feat_stats_d': {
    'tr': 'Detaylı takip',
    'en': 'Detailed tracking',
    'de': 'Detaillierte Verfolgung',
  },
  'premium_feat_ads_l': {
    'tr': 'Reklamsız',
    'en': 'Ad-free',
    'de': 'Ohne Werbung',
  },
  'premium_feat_ads_d': {
    'tr': 'Kesintisiz deneyim',
    'en': 'Uninterrupted experience',
    'de': 'Ununterbrochenes Erlebnis',
  },
  'premium_banner_headline': {
    'tr': 'Tam deneyim için\nPremium\'a geç',
    'en': 'Go Premium for\nthe full experience',
    'de': 'Premium für das\nvolle Erlebnis',
  },
  'prayer_offline_detail': {
    'tr': 'İnternet bağlantısı olmadan vakitler gösterilemiyor.',
    'en': 'Prayer times cannot be shown without an internet connection.',
    'de': 'Gebetszeiten sind ohne Internetverbindung nicht verfügbar.',
  },
  'continueReadingBadge': {
    'tr': 'OKUMAYA DEVAM',
    'en': 'CONTINUE READING',
    'de': 'WEITERLESEN',
  },
  'readingAyahShort': {
    'tr': '{n}. ayet',
    'en': 'Ayah {n}',
    'de': 'Ayah {n}',
  },
  'dashboardCountdownPrefix': {
    'tr': 'Kalan:',
    'en': 'Remaining:',
    'ar': 'المتبقي:',
    'ur': 'باقی:',
    'id': 'Sisa:',
    'fa': 'باقیمانده:',
    'bn': 'বাকি:',
    'ms': 'Tinggal:',
    'fr': 'Restant :',
    'de': 'Verbleibend:',
    'es': 'Restante:',
    'ru': 'Осталось:',
    'hi': 'शेष:',
    'sw': 'Imebaki:',
    'ml': 'ശേഷിക്കുന്നത്:',
    'uz': 'Qoldi:',
    'ps': 'پاتې:',
    'ha': 'Ya rage:',
    'ta': 'மீதம்:',
    'fil': 'Natitira:',
    'az': 'Qalıq:',
    'so': 'Harsan:',
  },
  'menuTitle': {
    'tr': 'Menü',
    'en': 'Menu',
    'ar': 'القائمة',
    'ur': 'مینو',
    'id': 'Menu',
    'fa': 'منو',
    'bn': 'মেনু',
    'ms': 'Menu',
    'fr': 'Menu',
    'de': 'Menü',
    'es': 'Menú',
    'ru': 'Меню',
    'hi': 'मेनू',
    'sw': 'Menyu',
    'ml': 'മെനു',
    'uz': 'Menyu',
    'ps': 'مینو',
    'ha': 'Menu',
    'ta': 'மெனு',
    'fil': 'Menu',
    'az': 'Menyu',
    'so': 'Menu',
  },
  'sidePremiumTitle': {
    'tr': 'Premium\'a Geç',
    'en': 'Go Premium',
    'ar': 'ترقية إلى بريميوم',
    'ur': 'پریمیم پر جائیں',
    'id': 'Jadi Premium',
    'fa': 'پریمیوم شوید',
    'bn': 'প্রিমিয়ামে যান',
    'ms': 'Naik taraf Premium',
    'fr': 'Passer à Premium',
    'de': 'Premium werden',
    'es': 'Hazte Premium',
    'ru': 'Перейти на Premium',
    'hi': 'प्रीमियम लें',
    'sw': 'Nenda Premium',
    'ml': 'പ്രീമിയത്തിലേക്ക്',
    'uz': 'Premiumga o‘tish',
    'ps': 'پریمیم ته لاړ شئ',
    'ha': 'Je Premium',
    'ta': 'பிரீமியம்',
    'fil': 'Mag-Premium',
    'az': 'Premiuma keç',
    'so': 'Premium u noqo',
  },
  'sidePremiumSubtitle': {
    'tr': 'Offline ses, tüm kariler, reklamsız',
    'en': 'Offline audio, all reciters, ad-free',
    'ar': 'صوت بدون إنترنت، كل القراء، بدون إعلانات',
    'ur': 'آف لائن آواز، تمام قاری، بغیر اشتہار',
    'id': 'Audio offline, semua qari, tanpa iklan',
    'fa': 'صوت آفلاین، همه قاری‌ها، بدون تبلیغ',
    'bn': 'অফলাইন অডিও, সব কারি, বিজ্ঞাপনমুক্ত',
    'ms': 'Audio luar talian, semua qari, tanpa iklan',
    'fr': 'Audio hors ligne, tous les récitants, sans pub',
    'de': 'Offline-Audio, alle Rezitatoren, werbefrei',
    'es': 'Audio sin conexión, todos los recitadores, sin anuncios',
    'ru': 'Офлайн-аудио, все чтецы, без рекламы',
    'hi': 'ऑफ़लाइन ऑडियो, सभी क़ारी, विज्ञापन-मुक्त',
    'sw': 'Sauti nje ya mtandao, wakari wote, bila matangazo',
    'ml': 'ഓഫ്‌ലൈൻ ഓഡിയോ, എല്ലാ ഖാരികളും, പരസ്യമില്ല',
    'uz': 'Offlayn audio, barcha qorilar, reklamasiz',
    'ps': 'آفلاین غږ، ټول قاریان، پرته له اعلانونو',
    'ha': 'Sauti offline, duka kar-kan, babu talla',
    'ta': 'ஆஃப்லைன் ஆடியோ, அனைத்து காரிகளும், விளம்பரமில்லை',
    'fil': 'Offline na audio, lahat ng reciter, walang ads',
    'az': 'Oflayn səs, bütün qarılar, reklamsız',
    'so': 'Cod offline, dhammaan karier-yada, aan xayeysiis',
  },
  'sideRateApp': {
    'tr': 'Uygulamayı Değerlendir',
    'en': 'Rate the app',
    'ar': 'قيّم التطبيق',
    'ur': 'ایپ کی درجہ بندی کریں',
    'id': 'Nilai aplikasi',
    'fa': 'امتیاز به اپ',
    'bn': 'অ্যাপ রেট করুন',
    'ms': 'Nilaikan aplikasi',
    'fr': 'Noter l’application',
    'de': 'App bewerten',
    'es': 'Valorar la app',
    'ru': 'Оценить приложение',
    'hi': 'ऐप रेट करें',
    'sw': 'Kadiria programu',
    'ml': 'ആപ്പ് റേറ്റ് ചെയ്യുക',
    'uz': 'Ilovani baholang',
    'ps': 'اپلیکیشن درجه‌بندي کړئ',
    'ha': 'Kimanta manhaja',
    'ta': 'பயன்பாட்டை மதிப்பிடு',
    'fil': 'I-rate ang app',
    'az': 'Tətbiqi qiymətləndirin',
    'so': 'Qiimee barnaamijka',
  },
  'sideRateLinkCopied': {
    'tr': 'Değerlendirme bağlantısı kopyalandı.',
    'en': 'Review link copied.',
    'ar': 'تم نسخ رابط التقييم.',
    'ur': 'جائزہ کا لنک کاپی ہو گیا۔',
    'id': 'Tautan ulasan disalin.',
    'fa': 'لینک نظرسنجی کپی شد.',
    'bn': 'রিভিউ লিঙ্ক কপি হয়েছে।',
    'ms': 'Pautan ulasan disalin.',
    'fr': 'Lien d’avis copié.',
    'de': 'Bewertungslink kopiert.',
    'es': 'Enlace de reseña copiado.',
    'ru': 'Ссылка на отзыв скопирована.',
    'hi': 'समीक्षा लिंक कॉपी हो गया।',
    'sw': 'Kiungo cha tathmini kimenakiliwa.',
    'ml': 'അവലോകന ലിങ്ക് പകർത്തി.',
    'uz': 'Sharh havolasi nusxalandi.',
    'ps': 'د بیاکتنې لینک کاپي شو.',
    'ha': 'An kwafa hanyar bita.',
    'ta': 'மதிப்பீட்டு இணைப்பு நகலெடுக்கப்பட்டது.',
    'fil': 'Nakopya ang review link.',
    'az': 'Rəy keçidi kopyalandı.',
    'so': 'Xiriirka dib u eegista waa la koobiyay.',
  },
  'sideShareApp': {
    'tr': 'Uygulamayı Paylaş',
    'en': 'Share app',
    'ar': 'مشاركة التطبيق',
    'ur': 'ایپ شیئر کریں',
    'id': 'Bagikan aplikasi',
    'fa': 'اشتراک‌گذاری اپ',
    'bn': 'অ্যাপ শেয়ার করুন',
    'ms': 'Kongsi aplikasi',
    'fr': 'Partager l’app',
    'de': 'App teilen',
    'es': 'Compartir app',
    'ru': 'Поделиться приложением',
    'hi': 'ऐप शेयर करें',
    'sw': 'Shiriki programu',
    'ml': 'ആപ്പ് പങ്കിടുക',
    'uz': 'Ilovani ulashing',
    'ps': 'اپلیکیشن شریک کړئ',
    'ha': 'Raba manhaja',
    'ta': 'பயன்பாட்டைப் பகிர்',
    'fil': 'Ibahagi ang app',
    'az': 'Tətbiqi paylaş',
    'so': 'Wadaag barnaamijka',
  },
  'sideShareText': {
    'tr': 'Noor Essence uygulamasını dene: {url}',
    'en': 'Try Noor Essence: {url}',
    'ar': 'جرّب Noor Essence: {url}',
    'ur': 'Noor Essence آزمائیں: {url}',
    'id': 'Coba Noor Essence: {url}',
    'fa': 'Noor Essence را امتحان کنید: {url}',
    'bn': 'Noor Essence ব্যবহার করে দেখুন: {url}',
    'ms': 'Cuba Noor Essence: {url}',
    'fr': 'Essayez Noor Essence : {url}',
    'de': 'Noor Essence ausprobieren: {url}',
    'es': 'Prueba Noor Essence: {url}',
    'ru': 'Попробуйте Noor Essence: {url}',
    'hi': 'Noor Essence आज़माएँ: {url}',
    'sw': 'Jaribu Noor Essence: {url}',
    'ml': 'Noor Essence പരീക്ഷിക്കുക: {url}',
    'uz': 'Noor Essence-ni sinab ko‘ring: {url}',
    'ps': 'Noor Essence وآزموئ: {url}',
    'ha': 'Gwada Noor Essence: {url}',
    'ta': 'Noor Essence-ஐ முயற்சிக்கவும்: {url}',
    'fil': 'Subukan ang Noor Essence: {url}',
    'az': 'Noor Essence sınayın: {url}',
    'so': 'Isku day Noor Essence: {url}',
  },
  'sideFooterTagline': {
    'tr': 'Dualarla yapıldı ✦',
    'en': 'Made with prayers ✦',
    'ar': 'صُنع بالدعاء ✦',
    'ur': 'دعاؤں سے بنایا گیا ✦',
    'id': 'Dibuat dengan doa ✦',
    'fa': 'با دعا ساخته شد ✦',
    'bn': 'দোয়ায় তৈরি ✦',
    'ms': 'Dibuat dengan doa ✦',
    'fr': 'Fait avec des prières ✦',
    'de': 'Mit Gebeten gemacht ✦',
    'es': 'Hecho con oraciones ✦',
    'ru': 'Сделано с молитвами ✦',
    'hi': 'दुआओं से बना ✦',
    'sw': 'Imetengenezwa kwa maombi ✦',
    'ml': 'പ്രാർത്ഥനകളോടെ ✦',
    'uz': 'Duolar bilan yaratilgan ✦',
    'ps': 'د لمانځه سره جوړ شوی ✦',
    'ha': 'An yi da addu\'o\'i ✦',
    'ta': 'பிரார்த்தனைகளுடன் ✦',
    'fil': 'Ginawa sa panalangin ✦',
    'az': 'Dualarla hazırlandı ✦',
    'so': 'Ku salaysan salaadda ✦',
  },
  'tabDownloadedSurahs': {
    'tr': 'İndirilenler',
    'en': 'Downloaded',
    'ar': 'المُحمَّلة',
    'ur': 'ڈاؤن لوڈ شدہ',
    'id': 'Diunduh',
    'fa': 'دانلودشده',
    'bn': 'ডাউনলোড করা',
    'ms': 'Dimuat turun',
    'fr': 'Téléchargées',
    'de': 'Heruntergeladen',
    'es': 'Descargadas',
    'ru': 'Скачанные',
    'hi': 'डाउनलोड',
    'sw': 'Zilizopakuliwa',
    'ml': 'ഡൗൺലോഡ് ചെയ്തവ',
    'uz': 'Yuklangan',
    'ps': 'ډاونلوډ شوي',
    'ha': 'An sauke',
    'ta': 'பதிவிறக்கப்பட்டவை',
    'fil': 'Na-download',
    'az': 'Yüklənənlər',
    'so': 'La soo dejiyay',
  },
  'downloadedSurahsEmpty': {
    'tr':
        'Henüz indirilmiş sure yok. Sure listesinden indirme yapabilirsiniz.',
    'en': 'No surahs downloaded yet. Download from the surah list.',
    'ar': 'لا توجد سور محمّلة بعد. نزّل من قائمة السور.',
    'ur': 'ابھی کوئی سورہ ڈاؤن لوڈ نہیں۔ فہرست سے ڈاؤن لوڈ کریں۔',
    'id': 'Belum ada surah diunduh. Unduh dari daftar surah.',
    'fa': 'هنوز سوره‌ای دانلود نشده. از فهرست دانلود کنید.',
    'bn': 'এখনও কোনো সূরা ডাউনলোড হয়নি। তালিকা থেকে ডাউনলোড করুন।',
    'ms': 'Tiada surah dimuat turun lagi. Muat turun dari senarai.',
    'fr': 'Aucune sourate téléchargée. Téléchargez depuis la liste.',
    'de': 'Noch keine Suren heruntergeladen. Von der Liste laden.',
    'es': 'Aún no hay suras descargadas. Descarga desde la lista.',
    'ru': 'Суры ещё не скачаны. Скачайте из списка.',
    'hi': 'अभी कोई सूरह डाउनलोड नहीं। सूची से डाउनलोड करें।',
    'sw': 'Bado hakuna sura zilizopakuliwa. Pakua kutoka orodha.',
    'ml': 'ഇതുവരെ സൂറകൾ ഡൗൺലോഡ് ചെയ്തിട്ടില്ല. പട്ടികയിൽ നിന്ന് ഡൗൺലോഡ് ചെയ്യുക.',
    'uz': 'Hali sura yuklanmagan. Ro‘yxatdan yuklang.',
    'ps': 'تر اوسه هیڅ سوره ډاونلوډ شوې نه دي. له لیست څخه ډاونلوډ کړئ.',
    'ha': 'Babu sura da aka sauko har yanzu. Sauke daga jerin.',
    'ta': 'இன்னும் சூராக்கள் பதிவிறக்கப்படவில்லை. பட்டியலில் இருந்து பதிவிறக்கவும்.',
    'fil': 'Wala pang na-download na surah. Mag-download mula sa listahan.',
    'az': 'Hələ yüklənmiş surə yoxdur. Siyahıdan yükləyin.',
    'so': 'Weli surah la soo dejin. Ka soo deji liiska.',
  },
  'savedSurahsEmpty': {
    'tr':
        'Henüz kaydedilmiş sure yok. Sure okuma sayfasındaki yer imi butonuyla kaydedebilirsiniz.',
    'en':
        'No saved surahs yet. Save from the bookmark button on the reading page.',
    'ar': 'لا توجد سور محفوظة بعد. احفظ من زر الإشارة في صفحة القراءة.',
    'ur': 'ابھی کوئی محفوظ سورہ نہیں۔ پڑھنے والے صفحے پر بک مارک بٹن سے محفوظ کریں۔',
    'id': 'Belum ada surah tersimpan. Simpan dari tombol penanda di halaman baca.',
    'fa': 'سوره‌ای ذخیره نشده. از دکمه نشانک در صفحهٔ خواندن ذخیره کنید.',
    'bn': 'এখনও কোনো সূরা সংরক্ষিত নয়। পড়ার পৃষ্ঠার বুকমার্ক বাটন দিয়ে সংরক্ষণ করুন।',
    'ms': 'Tiada surah disimpan lagi. Simpan dari butang penanda di halaman bacaan.',
    'fr': 'Aucune sourate enregistrée. Enregistrez via le signet sur la page de lecture.',
    'de': 'Noch keine Suren gespeichert. Über das Lesezeichen auf der Leseseite.',
    'es': 'Aún no hay suras guardadas. Guarda con el marcador en la lectura.',
    'ru': 'Нет сохранённых сур. Сохраните кнопкой закладки на странице чтения.',
    'hi': 'कोई सहेजी सूरह नहीं। पढ़ने वाले पृष्ठ पर बुकमार्क से सहेजें।',
    'sw': 'Bado hakuna sura zilizohifadhiwa. Hifadhi kwa kitufe cha alamisho kwenye kusoma.',
    'ml': 'സൂക്ഷിച്ച സൂറകൾ ഇല്ല. വായനാ പേജിലെ ബുക്ക്മാർക്ക് ബട്ടണിൽ നിന്ന് സൂക്ഷിക്കുക.',
    'uz': 'Saqlangan sura yo‘q. O‘qish sahifasidagi xatcho‘p tugmasi orqali saqlang.',
    'ps': 'هیڅ خوندي سوره نشته. د لوستلو پاڼې کې د بوکمارک تڼۍ سره خوندي کړئ.',
    'ha': 'Babu sura da aka adana har yanzu. Adana da maɓallin alama a shafin karatu.',
    'ta': 'சேமிக்கப்பட்ட சூராக்கள் இல்லை. வாசிப்புப் பக்கத்தில் புக்மார்க் பொத்தான் மூலம் சேமிக்கவும்.',
    'fil': 'Wala pang naka-save na surah. I-save gamit ang bookmark sa pahina ng pagbabasa.',
    'az': 'Hələ saxlanılmış surə yoxdur. Oxuma səhifəsindəki əlfəcin düyməsi ilə saxlayın.',
    'so': 'Weli surah la kaydin. Kaydi badhanka calaamadda bogga akhriska.',
  },
  'surahDownloadedSnackbar': {
    'tr': '{name} indirildi.',
    'en': '{name} downloaded.',
    'ar': 'تم تنزيل {name}.',
    'ur': '{name} ڈاؤن لوڈ ہو گیا۔',
    'id': '{name} diunduh.',
    'fa': '{name} دانلود شد.',
    'bn': '{name} ডাউনলোড হয়েছে।',
    'ms': '{name} dimuat turun.',
    'fr': '{name} téléchargée.',
    'de': '{name} heruntergeladen.',
    'es': '{name} descargada.',
    'ru': '{name} скачана.',
    'hi': '{name} डाउनलोड हो गई।',
    'sw': '{name} imepakuliwa.',
    'ml': '{name} ഡൗൺലോഡ് ചെയ്തു.',
    'uz': '{name} yuklandi.',
    'ps': '{name} ډاونلوډ شوه.',
    'ha': 'An sauke {name}.',
    'ta': '{name} பதிவிறக்கப்பட்டது.',
    'fil': 'Na-download ang {name}.',
    'az': '{name} yükləndi.',
    'so': '{name} waa la soo dejiyay.',
  },
  'snackDownloadFailedSurah': {
    'tr': 'İndirme başarısız. İnternet bağlantınızı kontrol edin.',
    'en': 'Download failed. Check your internet connection.',
    'ar': 'فشل التنزيل. تحقق من الاتصال.',
    'ur': 'ڈاؤن لوڈ ناکام۔ انٹرنیٹ چیک کریں۔',
    'id': 'Unduhan gagal. Periksa koneksi internet.',
    'fa': 'دانلود ناموفق. اتصال اینترنت را بررسی کنید.',
    'bn': 'ডাউনলোড ব্যর্থ। ইন্টারনেট পরীক্ষা করুন।',
    'ms': 'Muat turun gagal. Semak sambungan internet.',
    'fr': 'Échec du téléchargement. Vérifiez la connexion.',
    'de': 'Download fehlgeschlagen. Internet prüfen.',
    'es': 'Error al descargar. Comprueba la conexión.',
    'ru': 'Ошибка загрузки. Проверьте интернет.',
    'hi': 'डाउनलोड विफल। इंटरनेट जाँचें।',
    'sw': 'Upakuzi umeshindwa. Angalia mtandao.',
    'ml': 'ഡൗൺലോഡ് പരാജയപ്പെട്ടു. ഇന്റർനെറ്റ് പരിശോധിക്കുക.',
    'uz': 'Yuklab olish muvaffaqiyatsiz. Internetni tekshiring.',
    'ps': 'ډاونلوډ ناکام. انټرنټ وګورئ.',
    'ha': 'Saukarwa ta gaza. Duba haɗin intanet.',
    'ta': 'பதிவிறக்கம் தோல்வி. இணைப்பைச் சரிபார்க்கவும்.',
    'fil': 'Nabigo ang download. Suriin ang internet.',
    'az': 'Yükləmə uğursuz oldu. İnternetə baxın.',
    'so': 'Soo dejintu way fashilantay. Hubi internetka.',
  },
  'surahListOfflineCacheNotice': {
    'tr': 'Sureler çevrimdışı önbellekten yüklendi.',
    'en': 'Surahs loaded from offline cache.',
    'ar': 'تم تحميل السور من الذاكرة المؤقتة دون اتصال.',
    'ur': 'سورہیں آف لائن کیش سے لوڈ ہوئیں۔',
    'id': 'Surah dimuat dari cache offline.',
    'fa': 'سوره‌ها از حافظهٔ آفلاین بارگذاری شد.',
    'bn': 'সূরাগুলো অফলাইন ক্যাশ থেকে লোড হয়েছে।',
    'ms': 'Surah dimuat dari cache luar talian.',
    'fr': 'Sourates chargées depuis le cache hors ligne.',
    'de': 'Suren aus Offline-Cache geladen.',
    'es': 'Suras cargadas desde caché sin conexión.',
    'ru': 'Суры загружены из офлайн-кэша.',
    'hi': 'सूरह ऑफ़लाइन कैश से लोड हुईं।',
    'sw': 'Sura zilizopakiwa kutoka kwa akiba nje ya mtandao.',
    'ml': 'സൂറകൾ ഓഫ്‌ലൈൻ കാഷിൽ നിന്ന് ലോഡ് ചെയ്തു.',
    'uz': 'Suralar oflayn keshdan yuklandi.',
    'ps': 'سورې د آفلاین کش څخه بار شوې.',
    'ha': 'An loda sura daga cache na offline.',
    'ta': 'சூராக்கள் ஆஃப்லைன் கேசில் இருந்து ஏற்றப்பட்டன.',
    'fil': 'Na-load ang mga surah mula sa offline cache.',
    'az': 'Surələr oflayn keşdən yükləndi.',
    'so': 'Surah-yada laga soo shubay keydka offline.',
  },
  'premiumOfflineFeatureTitle': {
    'tr': 'Premium Özellik',
    'en': 'Premium feature',
    'de': 'Premium-Funktion',
  },
  'premiumOfflineDownloadBody': {
    'tr':
        'Offline ses indirme Premium üyelik gerektirir. Premium\'a geçerek tüm sureleri internetsiz dinleyebilirsiniz.',
    'en':
        'Offline audio download requires Premium. Go Premium to listen to all surahs without internet.',
    'de':
        'Offline-Audio-Download erfordert Premium. Werden Sie Premium, um alle Suren ohne Internet zu hören.',
  },
  'premiumNotNow': {
    'tr': 'Şimdi değil',
    'en': 'Not now',
    'de': 'Nicht jetzt',
  },
  'duaSearchHint': {
    'tr': 'Dua ara',
    'en': 'Search duas',
    'ar': 'ابحث عن الأدعية',
    'ur': 'دعائیں تلاش کریں',
    'id': 'Cari doa',
    'fa': 'جستجوی دعا',
    'bn': 'দোয়া খুঁজুন',
    'ms': 'Cari doa',
    'fr': 'Rechercher des invocations',
    'de': 'Duas suchen',
    'es': 'Buscar duas',
    'ru': 'Поиск дуа',
    'hi': 'दुआ खोजें',
    'sw': 'Tafuta maombi',
    'ml': 'ദുആ തിരയുക',
    'uz': 'Dua qidirish',
    'ps': 'دعا ولټوئ',
    'ha': 'Nemi addu\'a',
    'ta': 'துஆ தேடு',
    'fil': 'Maghanap ng dua',
    'az': 'Dua axtar',
    'so': 'Raadi duucooyinka',
  },
  'femaleVoiceLabel': {
    'tr': 'Kadın Sesi',
    'en': 'Female voice',
    'de': 'Stimme (weiblich)',
  },
  'maleVoiceLabel': {
    'tr': 'Erkek Sesi',
    'en': 'Male voice',
    'de': 'Stimme (männlich)',
  },
  'duaFemaleVoicePremiumSnack': {
    'tr': 'Kadın sesi Premium ile açılır.',
    'en': 'Female voice unlocks with Premium.',
    'de': 'Frauenstimme mit Premium freischalten.',
  },
  'duaReadLabel': {
    'tr': 'Okunuşu:',
    'en': 'Recitation:',
    'de': 'Rezitation:',
  },
  'duaMeaningLabel': {
    'tr': 'Anlamı:',
    'en': 'Meaning:',
    'de': 'Bedeutung:',
  },
  'duaListen': {
    'tr': 'Sesli Dinle',
    'en': 'Listen',
    'ar': 'استمع',
    'ur': 'سنیں',
    'id': 'Dengarkan',
    'fa': 'گوش کنید',
    'bn': 'শুনুন',
    'ms': 'Dengar',
    'fr': 'Écouter',
    'de': 'Anhören',
    'es': 'Escuchar',
    'ru': 'Слушать',
    'hi': 'सुनें',
    'sw': 'Sikiliza',
    'ml': 'കേൾക്കുക',
    'uz': 'Tinglang',
    'ps': 'واورئ',
    'ha': 'Saurari',
    'ta': 'கேள்',
    'fil': 'Pakinggan',
    'az': 'Dinlə',
    'so': 'Dhageyso',
  },
  'duaStop': {
    'tr': 'Durdur',
    'en': 'Stop',
    'ar': 'إيقاف',
    'ur': 'روکیں',
    'id': 'Berhenti',
    'fa': 'توقف',
    'bn': 'থামুন',
    'ms': 'Henti',
    'fr': 'Arrêter',
    'de': 'Stopp',
    'es': 'Detener',
    'ru': 'Стоп',
    'hi': 'रोकें',
    'sw': 'Simama',
    'ml': 'നിർത്തുക',
    'uz': 'To‘xtatish',
    'ps': 'درېدل',
    'ha': 'Tsaya',
    'ta': 'நிறுத்து',
    'fil': 'Ihinto',
    'az': 'Dayandır',
    'so': 'Jooji',
  },
  'duaDownloadPremiumSnack': {
    'tr': 'Dua indirme Premium gerektirir.',
    'en': 'Downloading duas requires Premium.',
    'de': 'Dua-Download erfordert Premium.',
  },
  'premiumShort': {
    'tr': 'Premium',
    'en': 'Premium',
    'de': 'Premium',
  },
  'qiblaCompassTitle': {
    'tr': 'Kıble Pusulası',
    'en': 'Qibla Compass',
    'de': 'Qibla-Kompass',
  },
  'labelMecca': {
    'tr': 'Mekke',
    'en': 'Mecca',
    'de': 'Mekka',
  },
  'qiblaFacingChip': {
    'tr': 'Kıble Yönü',
    'en': 'Qibla',
    'de': 'Qibla-Richtung',
  },
  'qiblaCompassActive': {
    'tr': 'Pusula Aktif',
    'en': 'Compass active',
    'de': 'Kompass aktiv',
  },
  'qiblaPermissionHeadline': {
    'tr': 'Konum İzni Gerekli',
    'en': 'Location permission required',
    'de': 'Standortberechtigung nötig',
  },
  'qiblaPermissionRequiredShort': {
    'tr': 'Konum izni gerekli',
    'en': 'Location permission needed',
    'de': 'Standortzugriff erforderlich',
  },
  'locationInfoLabel': {
    'tr': 'Konum',
    'en': 'Location',
    'de': 'Standort',
  },
  'locationAutoMode': {
    'tr': 'Otomatik',
    'en': 'Auto',
    'de': 'Automatisch',
  },
  'qiblaSensitivityShort': {
    'tr': 'Hassasiyet',
    'en': 'Accuracy',
    'de': 'Genauigkeit',
  },
  'accuracyLevelHigh': {
    'tr': 'Yüksek',
    'en': 'High',
    'de': 'Hoch',
  },
};

String? lookupAppExtra(String key, String languageCode) {
  final row = kAppExtra[key];
  if (row == null) return null;
  return row[languageCode] ?? row['en'];
}
